nodeLinker: node-modules
enableTelemetry: false
compressionLevel: mixed
defaultSemverRangePrefix: ""

# Enable zero-installs for faster CI/CD
enableGlobalCache: true

# Modern package management features
enableImmutableInstalls: false
